# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxasH0RXYbGwjCcIQPOVPFj4Vs1VlRgn
"""

import pandas as pd

# Malý dataset podobný Sakila
data = {
    "category": ["Action", "Comedy", "Drama", "Action", "Drama", "Comedy", "Action", "Drama", "Comedy", "Action"],
    "rental_id": [1,2,3,4,5,6,7,8,9,10]
}

df = pd.DataFrame(data)
print(df)



import pandas as pd

# Malý dataset podobný Sakila
data = {
    "category": ["Action", "Comedy", "Drama", "Action", "Drama", "Comedy", "Action", "Drama", "Comedy", "Action"],
    "rental_id": [1,2,3,4,5,6,7,8,9,10]
}

df = pd.DataFrame(data)
print(df)



import pandas as pd

# Malý dataset podobný Sakila
data = {
    "category": ["Action", "Comedy", "Drama", "Action", "Drama", "Comedy", "Action", "Drama", "Comedy", "Action"],
    "rental_id": [1,2,3,4,5,6,7,8,9,10]
}

df = pd.DataFrame(data)
print(df)

df_with_totals = df.merge(rentals_by_category, on="category")
print(df_with_totals)

# Počet prenájmov podľa kategórie
rentals_by_category = df.groupby("category")["rental_id"].count().reset_index()
rentals_by_category = rentals_by_category.rename(columns={"rental_id": "total_rentals"})
print(rentals_by_category)

import matplotlib.pyplot as plt

plt.bar(rentals_by_category["category"], rentals_by_category["total_rentals"], color="orange")
plt.title("Number of Rentals by Film Category")
plt.xlabel("Category")
plt.ylabel("Total Rentals")
plt.show()

plt.savefig("top_categories_chart.png")
plt.show()

import matplotlib.pyplot as plt

# Vykreslenie grafu
plt.bar(rentals_by_category["category"], rentals_by_category["total_rentals"], color="yellow")

# Najprv zobraz graf
plt.show()

# Potom ho ulož do súboru
plt.savefig("top_categories_chart.png")